### ISSUE TITLE
[240922] 이슈 테스트

### ISSUE THREAD

**Issue by Keun04** [Keun04/sea_otter#1]
### 이슈 탭 테스트 시작

이거 스터디 블로그처럼 남겨두면 되는건가?
가영아 댓글 달아봐

- [x] #2
- [x] 오 신기해

![푹다행1](https://github.com/user-attachments/assets/a9f4c3f6-fb3c-4cf9-a063-374e3560774c)\
이미지도 들어가요
@jgyeyang 

> 인용구

**Comment by Keun04** [comment]
1빠

**Comment by jgyeyang** [comment]
내가 왔더염

**Comment by Keun04** [comment]
> 내가 왔더염

인용답글
